<?php
use Innowise\Blog\Model\Post;
use Magento\Framework\View\Element\Template;

/** @var Post $post */
/** @var Template $block */
$postViewModel = $block->getData('post_view_model');
$post = $block->getData('post');

?>

<div class="post-wrapper">
    <a href="<?= $block->getUrl('blog/post/view', ['id' => $post->getData('post_id')]) ?>">
        <h3><?= $post->getData('title'); ?></h3>
    </a>
    <p>
        <span class="author">Pavel Ziuziun</span>
        <span class="published-date"><?= $block->formatDate($post->getData('created_at')); ?></span>
    </p>
    <p><?= $post->getData('content'); ?></p>
</div>


